//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityCard
    {
        public string IdentityCardId { get; set; }
        public int IdentityCardStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int PartnerId { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
