//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDetail
    {
        public int InventoryDetailId { get; set; }
        public float Weight { get; set; }
        public string Type { get; set; }
        public int InventoryId { get; set; }
        public int GoodsId { get; set; }
        public int PartnerId { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
