//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public int NotificationType { get; set; }
        public int StatusAdmin { get; set; }
        public int StatusPartner { get; set; }
        public string ContentForAdmin { get; set; }
        public string ContentForPartner { get; set; }
        public int PartnerId { get; set; }
        public int TransactionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
