//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ScheduleId { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public float RegisteredWeight { get; set; }
        public Nullable<float> ActualWeight { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int TransactionType { get; set; }
        public int ScheduleStatus { get; set; }
        public string UpdatedBy { get; set; }
        public int PartnerId { get; set; }
        public int GoodsId { get; set; }
        public int TimeTemplateItemId { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual TimeTemplateItem TimeTemplateItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
