//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTemplate()
        {
            this.TimeTemplateItems = new HashSet<TimeTemplateItem>();
        }
    
        public int TimeTemplateId { get; set; }
        public string TimeTemplateName { get; set; }
        public System.DateTime ApplyingDate { get; set; }
        public int TimeTemplateStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTemplateItem> TimeTemplateItems { get; set; }
    }
}
