//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTemplateItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTemplateItem()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int TimeTemplateItemId { get; set; }
        public float Inventory { get; set; }
        public System.TimeSpan ScheduleTime { get; set; }
        public int TimeTemplateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual TimeTemplate TimeTemplate { get; set; }
    }
}
