//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int TransactionId { get; set; }
        public System.DateTime TimeIn { get; set; }
        public System.DateTime TimeOut { get; set; }
        public float WeightIn { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Description { get; set; }
        public float WeightOut { get; set; }
        public bool IsScheduled { get; set; }
        public int TransactionType { get; set; }
        public int TransactionStatus { get; set; }
        public int PartnerId { get; set; }
        public string IdentificationCode { get; set; }
        public int GoodsId { get; set; }
        public string Gate { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
